### ISSUE TITLE
Where are the versions available

### ISSUE THREAD

**Issue by ziv1234** [XBMCil/service.subtitles.subscenter#19]
Probably a stupid question but couldn't find the answer. I installed the plugin from the Kodi repository. Now with the URL change the plugin doesn't work. Looks like it was fixed in 4.15 (thanks by the way), but when I ask Kodi to update, it still gives me the same version.

Is there any repository that I can install from? I can probably install manually, but this will break the update path, and I have a strong preference to automatic updates.

Any info?

**Comment by CaTzil** [comment]
Subscenter admin requested me to not publish the latest fix, u can download it manually.

**Comment by ziv1234** [comment]
Thanks. Do I just download it as Zip and give it to Kodi?

**Comment by ziv1234** [comment]
No worries. Installed 4.1.15. However, now the "check login details" works so I know it is pointing at the correct place. However, it doesn't find any subtitles. 

When I enable debug logs, it tells me:

12:08:40.795 T:140484103657216   DEBUG: ### [Subscenter.org] - Version: '4.1.5'
12:08:40.796 T:140484103657216   DEBUG: ### [Subscenter.org] - Action 'search' called
12:08:40.796 T:140484103657216   DEBUG: ### [Subscenter.org] - VideoPlayer.OriginalTitle not found
12:08:40.796 T:140484103657216   DEBUG: ### [Subscenter.org] - Item before cleaning:
                                                {'episode': '', 'temp': False, 'title': 'Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb.mkv', 'preferredlanguage': 'heb', 'season': '', 'year': '', 'rar': False, 'tvshow': '', 'file_original_path': u'smb://ZIV-PC/Downloads2/Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb[rarbg]/Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb.mkv', '3let_language': ['eng', 'heb']}
12:08:40.797 T:140484103657216   DEBUG: ### [Subscenter.org] - TV Parsed Item: {'episode': '9', 'temp': False, 'title': u'Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb', 'preferredlanguage': 'heb', 'season': '3', 'year': u'', 'rar': False, 'tvshow': u'Fargo', 'file_original_path': u'smb://ZIV-PC/Downloads2/Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb[rarbg]/Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb.mkv', '3let_language': ['eng', 'heb']}
12:08:40.797 T:140484103657216   DEBUG: ### [Subscenter.org] - {'episode': '9', 'temp': False, 'title': u'Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb', 'preferredlanguage': 'heb', 'season': '3', 'year': u'', 'rar': False, 'tvshow': u'Fargo', 'file_original_path': u'smb://ZIV-PC/Downloads2/Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb[rarbg]/Fargo.S03E09.Aporia.1080p.NF.WEBRip.DD5.1.x264-NTb.mkv', '3let_language': ['eng', 'heb']}
12:08:40.849 T:140484103657216   DEBUG: ### [Subscenter.org] - Getting url: http://www.subscenter.info/he/api/search/
12:08:40.849 T:140484103657216   DEBUG: ### [Subscenter.org] - Post Data: episode=9&season=3&q=Fargo&token=4n6-9e1c41f1b8ee22efdec6&user=298222&type=series
12:08:41.282 T:140484555044608 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:08:41.381 T:140484103657216   DEBUG: ### [Subscenter.org] - Failed to get url: http://www.subscenter.info/he/api/search/
                                            HTTP Error 404: NOT FOUND
12:08:41.381 T:140484103657216   DEBUG: ### [Subscenter.org] - Results: None
12:08:41.381 T:140484103657216    INFO: CPythonInvoker(4, /home/ziv/.kodi/addons/service.subtitles.subscenter/service.py): script successfully run

Any ideas? Do I need to upgrade to 5.0? Is it stable?

**Comment by ziv1234** [comment]
Looks like 5.0 solves this issue. However, when I do "check login details", it fails. When I go into a video and download subtitles, it works. Obviously less important since I dont change my login details too often, but just in case, here is the error log that I get:

12:21:10.388 T:139754595145472   DEBUG: ### [Subscenter.org] - Getting url: http://www.subscenter.info/he/login/
12:21:10.612 T:139754595145472   DEBUG: ### [Subscenter.org] - Failed to get url: http://www.subscenter.info/he/login/
                                            HTTP Error 404: NOT FOUND
12:21:10.613 T:139754595145472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/ziv/.kodi/addons/service.subtitles.subscenter/service.py", line 232, in <module>
                                                helper.login(True)
                                              File "/home/ziv/.kodi/addons/service.subtitles.subscenter/resources/lib/SUBUtilities.py", line 288, in login
                                                if content['result'] == 'success':
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
12:21:10.618 T:139756521906368   DEBUG: ------ Window Init (DialogNotification.xml) ------
12:21:10.633 T:139754595145472    INFO: Python script stopped
12:21:10.633 T:139754595145472   DEBUG: Thread LanguageInvoker 139754595145472 terminating
12:21:12.982 T:139756521906368   DEBUG: ------ Window Init (Pointer.xml) ------
12:21:16.341 T:139756521906368   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

**Comment by CaTzil** [comment]
The current method not requires login, that was left from the API approach.

I`ve removed it, thanx.

**Comment by ziv1234** [comment]
Thanks for the quick replies!

On 24 Jun 2017, at 13:22, CaTz <notifications@github.com> wrote:

The current method not requires login, that was left from the API approach.

I`ve removed it, thanx.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/XBMCil/service.subtitles.subscenter/issues/19#issuecomment-310830244>,
or mute the thread

**Comment by CaTzil** [comment]
I`ve released 5.0.1 that removes the ability to enter login credentials.
