### ISSUE TITLE
Addons arrives with pre configured credentials.

### ISSUE THREAD

**Issue by Dwebs1** [XBMCil/service.subtitles.subscenter#21]
The addon arrived with pre confgigued credebtials.
In order to succusfully login, you should default values so it will come up clean and then write your own credentials. 
Trying to manually write the credentials make failures.
For your attention

**Comment by CaTzil** [comment]
https://github.com/XBMCil/service.subtitles.subscenter/blob/master/resources/settings.xml#L4-L5
https://github.com/XBMCil/service.subtitles.subscenter/blob/master/resources/lib/SUBUtilities.py#L281-L282
Those are the only places that touches Email / Password fields, there is no any predefined vals there.
It can be that you had previous credentials, and now it just uses it.
