### ISSUE TITLE
possible language mismatch bug

### ISSUE THREAD

**Issue by hedwigz** [XBMCil/service.subtitles.subscenter#3]
היי, קודם כל, הרבה תודה על התוסף המדהים הזה, עשיתם עבודה ממש טובה.
שמתי לב שהתוסף לא תמיד עובד כמו שצריך, למשל אתמול כשניסיתי לצפות בסדרה "חסר גבולות" דרך התוסף ג'נסיס.
מה שקרה זה שהחיפוש לא הניב אף תוצאות.
הורדתי את הקוד והתחלתי להוסיף קצת לוגים ולראות מה קורה.
שמתי לב שיש קטע קוד:
https://github.com/XBMCil/service.subtitles.subscenter/blob/master/resources/lib/SUBUtilities.py#L196
שבודק האם השפה של קודי נמצאת ב
3let_language
 של ה
item,
ואם היא לא מוצאת שם
heb
אז היא לא מחפשת כתוביות. זה קרה לי **למרות שהקודי שלי מוגדר לעברית**.
בנוסף, שמתי לב שמשתמשים בכתובת הישנה של סאבסנטר
(הם שינו ל subscenter.cinemast)
ככה שיכול להיות שצריך לעבור לכתובת החדשה לפני שהישנה כבר לא תיתמך?
בכל מקרה, אשמח לשמוע את דעתך על הבעיה ושנמצא לה פתרון (כרגע הוספתי item["3let_language"].append('heb')
 כדי להוסיף את
heb
ידנית) - ערבי, אבל עובד בינתיים.
סופש נעים!
עמית

**Comment by CaTzil** [comment]
היי,
תוספי הכתוביות נועדו לעבוד עבור תוכן שקודי סרקה, ז"א קודי הכניסה את הסרט / סדרה למאגר.
במקרה וזה המצב, תוספי הכתוביות עובדים כמו שצריך זאת כיוון שקודי דואג להעביר את כל המידע הדרוש.

עם הזמן, החלו לצוץ תספים שונים ומשונים כדוגמת Genesis שלא מעבירים את כל המידע, ובלי מידע זה התוסף לא אמור לעבוד.
אני לא הולך להפר את ה-API שקודי מכתיב על מנת לתמוך בכל התוספים שקמים כל שני וחמישי, ולפגוע בצורת העבודה התקינה, ניסיתי בעבר, וזה גרם לבאגים אצל משתמשים אחרים.
לדוגמא במקרה שלך, אם אכניס בכוח את השפה המבוקשת של עברית, הרי שהתוסף יציג כתוביות בעברית לאנשים שלא בחרו בעברית, אז נכון עבורך זה פתר את הבעיה, אולם לאחרים זה חשף באג.

ולכן, כהחלטה, כל תוסף שרוצה לעבוד עם תוספי הכתוביות כמו שצריך, אמור לממש את ההגדרות שקודי מכתיב, תוסף שלא יעשה את זה, תוסף הכתוביות לא יעבוד אצלו בצורה תקינה, כמו שציינת, לפעמים התוסף עובד אצלך ולפעמים לא.
כיוון שזה פרוייקט בקוד פתוח, אתה מוזמן לעשות עם הקוד מה שאתה רוצה. זכותך.

לכבי הכתובת הישנה, כל עוד זה עובד, אין שום סיבה לשנות, לכשתשתנה הכתובת, אני אעדכן את הקוד בהתאם. (זה לא יקרה בקרוב).
להבא, בבקשה באנגלית.

**Comment by sagiben** [comment]
היי @amits1995 ,
לגבי
3let_language
אתה לא צריך להוסיף את זה ידנית
עליך להוסיף את עיברית דרך ההגדרות של קודי ב
System --> Video --> Subtitles --> Languages to download subtitles for
ולבחור את שפות הכתוביות

**Comment by hedwigz** [comment]
היי,
כל הגדרות העברית האפשריות - עשיתי.
גם ברמה של ג'נסיס, גם ברמה של הממשק וגם ברמה של מה שכתבת.
משום מה לא עבד עם ג'נסיס.
בכל מקרה, כתבתי היום סקריפט לווינדוס שמאפשר לעשות מקש ימני על קובץ (של סרט או פרק מסדרה) וזה מוריד אוטומטית את הכתוביות המתאימות לתיקייה. כמובן, זה משתמש בקוד שלכם. שיניתי את תצורת קביעת התאימות בעזרת חבילה בשם guessit (היא מפרסרת טוב את פרטי הקובץ מהשם שלו). נשמע לכם משהו ששווה לפרסם? (לי אישית זה מאוד שימושי)
