### ISSUE TITLE
looks like not working since v 4.0.1

### ISSUE THREAD

**Issue by hedwigz** [XBMCil/service.subtitles.subscenter#5]
here's the error
22:39:04 T:23372   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '**getitem**'
                                            Traceback (most recent call last):
                                              File "C:\Users\Amit\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\service.py", line 151, in <module>
                                                search(item)
                                              File "C:\Users\Amit\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\service.py", line 32, in search
                                                subtitles_list = helper.get_subtitle_list(item)
                                              File "C:\Users\Amit\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\resources\lib\SUBUtilities.py", line 126, in get_subtitle_list
                                                search_results = self._search(item)
                                              File "C:\Users\Amit\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\resources\lib\SUBUtilities.py", line 138, in _search
                                                query = {"q": search_string.encode("utf-8"), "user": user_token["user"], "token": user_token["token"]}
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
22:39:04 T:17736   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.subscenter/?action=search&languages=English%2cHebrew&preferredlanguage=Undetermined

**Comment by hedwigz** [comment]
Found what the problem is:  
in  https://github.com/XBMCil/service.subtitles.subscenter/blob/master/resources/lib/SUBUtilities.py#L298  
When no data is in store it returns the string "null" and the if is then successfull.
We should change the if condition to:
if results != "null":

**Comment by CaTzil** [comment]
I can`t reproduce your issue at my stations (win & linux).
What OS do you have?
Can you supply reproduction steps?

**Comment by hedwigz** [comment]
Hi,
Happens on both Kodi 15.2 and 16.
On my friend's Windows 7 HTPC, another friend android box, my android box.
And finally on my Windows 10 PC where I debugged the issue.
This happens when the store (StorageServer) doesn't have previous data for the key "credentials"
and the return value is THE STRING "null". I don't know exactly what steps you should take to reproduce this. Maybe try cleaning your StorageServer somehow?
My guess is that you already have credentials on it. otherwise, what return value do you get from line 297?

**Comment by CaTzil** [comment]
I`ve cleaned the entry, and tried to download.
Did you configured an Email & password?

**Comment by hedwigz** [comment]
Yes, valid email and password. Though it doesn't matter cause the flow I
described precedes the login attempt..

**Comment by CaTzil** [comment]
OK,
I`ve found the edge case, you have tried to download a sub before setting up the credentials.
The credentials that were cached are the string "null", and after that even if you enter the right credentials it will fail.

I`ve fixed that scenario.
In order to fix it at your comps, clear the cache using the addon`s settings.
Check that the credentials are correct and then try to search.
Anyway i will publish a fix for that tomorrow.

**Comment by hedwigz** [comment]
Awesome! Thank you

**Comment by CaTzil** [comment]
You can try the fix, don`t forget to clean the cache.

**Comment by hedwigz** [comment]
Will do, tomorrow :)

**Comment by CaTzil** [comment]
Any updates?

**Comment by hedwigz** [comment]
Yeah, sorry, the fix works

**Comment by hedwigz** [comment]
But may I suggest that you support the case where the value is "null" cause most users with that error won't understand why they are getting "email or password incorrect" though they did fill email and password..

**Comment by CaTzil** [comment]
It not suppose to fill the store with that value anymore.

**Comment by hedwigz** [comment]
But may I suggest that you support the case where the value is "null" cause most users with that error won't understand why they are getting "email or password incorrect" though they did fill email and password..  
To clarify: if I would not have cleaned my cache the new version wouldn't work yet and will show "email or password incorrect" (tested that scenario) though they are correct  
Most users didn't fill email & password prior to version 4 and therefore I believe most users will have "broken cache" which they won't clean like me cause they don't know the root of the problem..

**Comment by CaTzil** [comment]
OK, i will check complains in the Forums/Facebook and if that will raise i will fix it.
Thank you

**Comment by hedwigz** [comment]
Thank you again
May I ask what forum/Facebook groups so that I can follow aswell?

**Comment by sagiben** [comment]
I had the same issue, and had to clean the cache.

Sagi.

**Comment by CaTzil** [comment]
Hometheater,
Kodi-israel -- fb group
